# Generated by Django 5.2.17 on 2026-08-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedtestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Виконується'), ('done', 'Завершено'), ('error', 'Помилка')], default='running', max_length=10)),
                ('download_mbps', models.FloatField(blank=True, null=True)),
                ('upload_mbps', models.FloatField(blank=True, null=True)),
                ('ping_ms', models.FloatField(blank=True, null=True)),
                ('server_name', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
